### ISSUE TITLE
Monkey patch breaks request.post()

### ISSUE THREAD

**Issue by 3XE** [msabramo/requests-unixsocket#16] opened 2016-03-15 13:59 UTC
With the monkey patch technique (and perhaps others, I have not checked) requests.post() appears to break on both socket and standard TCP/IP connections.  E.g.

    import requests
    import requests_unixsocket
    
    requests_unixsocket.monkeypatch()
    
    r = requests.post('http+unix://%2Fvar%2Frun%2Fexample.sock/example-endpoint')
    #TypeError: request() got an unexpected keyword argument 'json'

    r = requests.post('http://eample.com')
    #TypeError: request() got an unexpected keyword argument 'json'

I have submitted PR #17  which appears to fix the issue.

Thanks for this package btw!

-Peter

**Comment by msabramo** [comment] 2016-08-01 15:35
Thanks for your report and PR!

Hmmmm, I'm not able to reproduce this on the `master` branch:

```
$ ipython
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16)
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import requests

In [2]: import requests_unixsocket

In [3]: requests_unixsocket.monkeypatch()
Out[3]: <requests_unixsocket.monkeypatch at 0x105aed350>

In [4]: r = requests.post('http+unix://%2Fvar%2Frun%2Fdocker.sock/example-endpoint')

In [5]: r
Out[5]: <Response [404]>
```

Are you still seeing this?

**Comment by msabramo** [comment] 2016-08-01 15:38
I also can't reproduce with a packaged version:

```
$ pip freeze | grep requests-unixsocket
requests-unixsocket==0.1.5

$ ipython
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import requests

In [2]: import requests_unixsocket

In [3]: requests_unixsocket.monkeypatch()
Out[3]: <requests_unixsocket.monkeypatch at 0x10686ef90>

In [4]: r = requests.post('http+unix://%2Fvar%2Frun%2Fdocker.sock/example-endpoint')

In [5]: r
Out[5]: <Response [404]>
```

**Comment by msabramo** [comment] 2016-08-01 16:08
@3XE: If you are still seeing this, then please let me know the output of `pip freeze | grep requests`.

**Comment by msabramo** [comment] 2016-08-01 16:09
I wonder if 89166cf951030cf61241983337fd7ffd2536878a fixed the issue that you were seeing and you had been using a version that didn't have that.

**Comment by msabramo** [comment] 2016-08-01 16:13
I'm going to close this and the PR (#17) for now, since I can't reproduce the issue. If you can show me how to reproduce, I'll reopen.

Thanks!

**Closed by msabramo** 2016-08-01 16:13 UTC
